class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.53.tar.gz"
  sha256 "ea014d1c81e26a959385ad0740294227388ec9236d0c1acd9e576176c3e9b820"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "83f6ddb499f170dbe5b5e03406656dc31f273e6ef8694d472ad4a2611e1f1e58"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "83f6ddb499f170dbe5b5e03406656dc31f273e6ef8694d472ad4a2611e1f1e58"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "83f6ddb499f170dbe5b5e03406656dc31f273e6ef8694d472ad4a2611e1f1e58"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "aef90f5b768fe38be3b882533ad3ea146dc2c087ec706525302ae7df67cb2551"
    sha256 cellar: :any,                 x86_64_linux:  "fbd60c24a27fc6aebd74ddd927de5e4010bbe28227e20ba6ccf57ab255915f3a"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
