class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.54.tar.gz"
  sha256 "c2d4083baa88d039b0effdec6464e207c48574d6854dc3ffbde4535e8807475c"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "dc8a9ea3f430fc817e2b84df0341b5393ee147afa04b660c5050a4e99ac38a61"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "dc8a9ea3f430fc817e2b84df0341b5393ee147afa04b660c5050a4e99ac38a61"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "dc8a9ea3f430fc817e2b84df0341b5393ee147afa04b660c5050a4e99ac38a61"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "dc1358f5ec4b3ef633554cc38eead0872385a88852d06e0fd2b6dda24a1a3f3a"
    sha256 cellar: :any,                 x86_64_linux:  "e13fab54edb7842bf8de87e89c5a9afdb9bd5c133cb5356fea793c4885344f02"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
